"""Increase phone field length for encrypted data

Revision ID: a2bc2434c7b2
Revises: 
Create Date: 2025-10-13 14:47:53.051510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bc2434c7b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_comment='手机号',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_comment='手机号',
               existing_nullable=True)
    # ### end Alembic commands ###
